apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/adorsys/keycloak-ssi-deployment.git'
    targetRevision: improved-helm-chart-deployment
    path: keycloak-chart
    helm:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: datev-wallet
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncWave: 0